# logstash - indexer instance
#

description     "logstash indexer instance"

start on virtual-filesystems
stop on runlevel [06]

respawn
respawn limit 5 30

#env JAVA_OPTS='-Xms512m -Xmx512m'
chdir /srv/logstash
setuid logstash
setgid logstash
console log

script
  exec java -jar /usr/share/logstash/logstash-1.1.1-monolithic.jar agent -f /etc/logstash/ --log /srv/logstash/log/agent.out
end script
